#!/bin/sh
set -e
package_name=cinnamon-biglinux
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/xsessions/cinnamon2d.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/xsessions/cinnamon.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/xsessions/cinnamon2d.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/xsessions/cinnamon.desktop"
;;
esac
exit 0
